### ISSUE TITLE
Py error on func-hint

### ISSUE THREAD

**Issue by Alexey-T** [TomBraider42/cuda_autoit_helper#2]
new Autoit file.
after "Dec(" i call func-hint.

Console error
```
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "/home/user/.cudatext/py/cuda_autoit_helper/__init__.py", line 15, in __init__
    for line in fin:
  File "/usr/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x97 in position 509: invalid start byte
```

If you have file with non ascii text, Linux reads it such

**Comment by TomBraider42** [comment]
Using
`with codecs.open(<AutoIt.acp>, 'r', encoding='utf-8', errors='ignore') as fin:`
works for me now with UTF-8 and ANSI files.
